# Generated by Django 4.1.1 on 2022-09-18 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("listing_app", "0002_listingsapp_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listingsapp",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listingsApp_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
